name: Release

on:
  push:
    branches:
      - master
      - fix-cache-error

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: "Versions"
      run: |
        cat /etc/os-release
        node --version
        npm --version
    # - uses: actions/cache@v2
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-
    - run: rm -rf package-lock.json
    - run: npm i
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
    - run: git
    - run: npm run lint
    - run: npm test

  # gh-pages:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'

  #     - uses: actions/cache@v2
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  #     - run: npm ci
  #     - run: npm run dist
  #     - run: npm run dist-mocktimes

  #     - name: Deploy
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist
